CREATE TABLE rabbitmq
(
       ID NUMERIC(10) NOT NULL,
       MESSAGE CHARACTER VARYING(25000)
);

CREATE TABLE restemplate
(
       ID NUMERIC(10) NOT NULL,
       MESSAGE CHARACTER VARYING(25000)
);